print("                     .          +------------------------+")
print("                    / V\\--------|Java è melglio di python|")
print("                  / `  /        +------------------------+")
print("                 <<   |")
print("                 /    |")
print("               /      |")
print("             /        |")
print("           /    \  \ /")
print("          (      ) | |")
print("  ________|   _/_  | |")
print("<__________\______)\__)")